export { default as boyGroups } from "./boy-group"
export { default as bGroup } from "./boy-group/bGroup"
export { default as girlGroups } from "./girl-group"
export { default as gGroup } from "./girl-group/gGroup"
export { default as Footer } from "./footer"
export { default as Misc } from "./misc"
export { default as Navbar } from "./navbar"
export { default as News } from "./news"
export { default as Quiz } from "./quiz"
export { default as Default } from "./Default"

